version: "3.8"
services:
  wedding-next-js:
    build: ./
    container_name: next-js
    restart: always
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    links:
      - wedding-mongodb
  wedding-mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
