version: "3"
services:
  wedding-next-js:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: next-js
    restart: always
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    links:
      - wedding-mongodb
  wedding-mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    ports:
      - "27017:27017"
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example
